### PR TITLE
Created a gallery component

### PR DESCRIPTION
**Pull request by clc80**
I didn't see any pictures in the static folder to really add. The way it would work is that images would be passed in from the parent component via 
```
let urls=[
"/static/<image.name>", 
"/static/<image.name>"
];
```

### CODE REVIEW

**Review by majordwarf — CHANGES_REQUESTED** [review]
Hey Claudia, thanks for the PR! But here are some of the issues.

1. Yeah there are no images in `static` directory because right now there are none. Thus, there was a link to already existing gallery to take inspiration along with images. You may use a GraphQL query to fetch images from a specific directory and then render them all rather than having a manual entry every time you insert new images. So if you are storing images in `static/gallery/`, you query that folder and display all images in it. You may at the already existing code to get a gist of GraphQL queries and how to use them, also [this](https://stackoverflow.com/questions/51349801/querying-all-images-in-folder-using-graphql) might be helpful.
2. We are using .jsx file format for every component and page files. Keeping every file in same format would be helpful.
3. Also we are using React's functional components instead of class components. React functional compenents does the same task but less line while making it easier for others to read, test and maintain.

**Comment by Cervator** [comment]
`src/.DS_Store` should probably also be added to the `.gitignore` as well, instead of committed :-)

Thanks for the PR!

**Comment by Cervator** [comment]
@clc80 actually, on second thought, I'm a little confused here. It looks like your contribution is just a copy paste of a snippet from https://www.javascriptstuff.com/react-image-gallery/ (or some similar source for the same snippet), and as @majordwarf comments it doesn't really fit into our code base at all, nor is it exercised in any way that would be testable, like by adding a placeholder image or two.

The idea is really to _add_ something, and attribute any utility stuff you grab off the internet as part of your work in putting that utility stuff to work doing something new and useful here. Then test it in some fashion, ideally providing a screenshot of it working in a test setup, or better yet upload a copy of the updated site somewhere we can reach to look at the changes.

**Comment by Cervator** [comment]
Closing this from lack of follow-up + #22 also implemented an approach for gallery functionality.

**Pull request closed without merging**
