### PR TITLE
fix: Game page

### PR DESCRIPTION
**Pull request by ryuk156**
This PR  deals with the issue of Image quality of Game page images and also improve the UI of Game page

Screenshot:
image

### CODE REVIEW

**Comment by jdrueckert** [comment]
On seeing it in the GitPod deployment I agree with @majordwarf that the bolder font looks weird.
Can we reset this to the normal font thickness? Maybe it only appeared hard to read in the small screenshot but on screen it actually works fine...? Let's see.

**Comment by ryuk156** [comment]
> On seeing it in the GitPod deployment I agree with @majordwarf that the bolder font looks weird.
> Can we reset this to the normal font thickness? Maybe it only appeared hard to read in the small screenshot but on screen it actually works fine...? Let's see.

Done

**Comment by jdrueckert** [comment]
Nitpick: I feel like the text margin to the left/right (the closer image border) is too small. Can we make it the same as the top margin?

**Comment by ryuk156** [comment]
> Nitpick: I feel like the text margin to the left/right (the closer image border) is too small. Can we make it the same as the top margin?

done

**Review by majordwarf — APPROVED** [review]

**Pull request merged**
